### ISSUE TITLE
Allow configuration of #digit + period

### ISSUE THREAD

**Issue by evandrix** [pcarrier/gauth#33]
Some RFC6238 TOTP implementations use digits other than 6, or periods other than 30s e.g. Fortinet uses 60s

**Comment by pcarrier** [comment]
@evandrix Would you have a pointer to how they would represent that in whatever they pass to you so we can take a stab at it? [RFC6238](https://www.rfc-editor.org/rfc/inline-errata/rfc6238.html) doesn't bother with representation.

**Comment by creachadair** [comment]
One common tactic is the `otpauth` URL scheme (https://github.com/google/google-authenticator/wiki/Key-Uri-Format). This is how applications that use QR codes usually encode their settings.

I did some light hacking on this issue. One reasonable approach is to extend the reader to look for how many fields are in the config line. If it's 2 (as now), treat it as a secret with default settings; if it's > 2, use the additional fields for other settings. This has the nice property that it works with `otpauth` format:

```
# Standard
configname:secret

# URL
configname:otpauth://blah/¬

# Ad-hoc
configname:secret:period=n,length=m,etc
```

Another approach I tried that also works is to special-case the 2-field format for the name `otpauth` and a "secret" beginning with `//`, e.g.,

```
otpauth://configname/…
```

This is a little more subtle, but averts the duplication of config names. It doesn't introduce any regressions for existing files, since `//` is not a valid component of a base32 secret string, so such a line would already be rejected.

I stalled on this because it changes the output: When different settings can have different periods, the "countdown" section is no longer normative. We could change it so that each line has its own countdown, or GCD the shared countdown until the next period reset. I wasn't convinced there was enough interest in this issue to chase that particular rabbit at the time.

**Comment by pcarrier** [comment]
We could also read line by line distinguishing between `[^:]:[^:]+` and `[^:]:$`, switching a multi-line mode upon the latter that ends with a newline.

This would allow for:

```
foo:somesecret

bar:
secret: othersecret
period: n

quz:last-secret-i-swear
```

Might even already be using a subset of HJSON or YAML or JSON5 or [...] where we're already defining a map, in which case we could switch a "proper" language with straightforward polymorphism to handle.

**Comment by creachadair** [comment]
Agreed, the options I tried were intentionally minimalistic. I implemented an [`otpauth`](https://pkg.go.dev/github.com/creachadair/otp/otpauth) subpackage we could use if you do want to parse those URLs.

**Comment by pcarrier** [comment]
I think this is solved now that we use otpauth and support arbitrary URLs?

**Comment by creachadair** [comment]
I believe so, yes. One can write, e.g., `otpauth://totp/servicename?digits=8&period=60` for (say) 8 digits and a 60-second refresh. Note, though, that the output for "time remaining" is hardwired to 30 seconds, so it won't show the right time-remaining currently.
